### ISSUE TITLE
Player count freezes when players reach 100.

### ISSUE THREAD

**Issue by Faqahat** [dennorske/samp-packet-proxy#6] opened 2020-04-18 10:17 UTC
So when the server reaches 100+ players the player count is frozen at 100 even if the player count drops below 100 we have to restart the script.

**Comment by dennorske** [comment] 2020-04-18 10:21
Strange!

Has it happened multiple times?

I am aware that the script can freeze and needs a little restart once in a while, because I am not familiar with it breaking at 100 players specifically. The same behaviour is when it locks up regularly as well, player count doesn't change.

**Comment by Faqahat** [comment] 2020-04-18 15:29
It happens every time the player count reaches 100. So the count will never cross 100 nor will it drop so every time the count reaches 100 it just freezes there. There is another problem I noticed today and weirdly so everything was alright and suddenly the query parameters got messed up somehow. I was able to capture a SS, 
![image](https://user-images.githubusercontent.com/12972150/79641786-0e768980-81b3-11ea-8aa2-33385f59e413.png)
In the screenshot you cans ee server is locked "which was not" the max player is set 49 (49 was the actual player count) and you can see a few server parameters in players list too.
I had to remove all IPtable rules to fix it however this problem was not consistent it changes on every query request sometimes it showed server name in players list changed maxplayers to players count, displayed parameters like mapname lagcomp in players list or even added players name's in server parameters... i started using the script today after a long time

**Comment by dennorske** [comment] 2020-04-18 22:18
Thank you for the report, I will look into this.
I need to see if I can reproduce the bug, because I'd need to dump the ncat logs to analyse the packets, to understand the issue :) 

Edit: I realise that a locked server may send different packages, and this can cause everything to shift. I'll have a look

**Comment by dennorske** [comment] 2020-04-20 09:53
May I know what your server name and IP is, for reference and for testing the byte lengths? 
You can mail me at fox@floof.cc if you don't want it public.

**Comment by Faqahat** [comment] 2020-04-20 11:40
> May I know what your server name and IP is, for reference and for testing the byte lengths?
> You can mail me at [fox@floof.cc](mailto:fox@floof.cc) if you don't want it public.

I have mailed you the IP Address.

**Comment by 0xKeltic** [comment] 2020-08-01 11:13
This happened to my server when reach 60 players.

**Comment by dennorske** [comment] 2020-08-01 11:18
Hi Hispano!

Can you provide me with a 5 second TCPdump from your server to provide with the payloads / data that goes to your SA-MP port? 

It will greatly help me identify the issue with high playercounts

**Comment by 0xKeltic** [comment] 2020-08-01 11:39
> 
> 
> Hi Hispano!
> 
> Can you provide me with a 5 second TCPdump from your server to provide with the payloads / data that goes to your SA-MP port?
> 
> It will greatly help me identify the issue with high playercounts

Sure, i will send you a e-mail.

And thanks for the script, a looser is attacking my server 24/7 with qattack

**Comment by dennorske** [comment] 2020-08-01 17:32
Thanks for the data you provided on the email. I will look into it very shortly, currently on vacation. @nickdodd25 you around?

**Comment by dennorske** [comment] 2021-03-19 21:28
Fixed in da3e0c2

**Closed as completed** 2021-03-19 21:33 UTC
Labels: bug
